// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfYc8shmH60BUSamhnHrtKN4E0qGqrnII',
    appId: '1:133861736811:web:d4877c9e86b8ff749c4c2e',
    messagingSenderId: '133861736811',
    projectId: 'mensameetdatabase',
    authDomain: 'mensameetdatabase.firebaseapp.com',
    storageBucket: 'mensameetdatabase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB5BDzR8MZV2LSDwUHYpXmtyAgUTgHf9E',
    appId: '1:133861736811:android:469e000a5609d68f9c4c2e',
    messagingSenderId: '133861736811',
    projectId: 'mensameetdatabase',
    storageBucket: 'mensameetdatabase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRFTEOZPfUoUJCvvh6SdUmRZ0UQlE2Xx8',
    appId: '1:133861736811:ios:d6f11ac2ca4e68f59c4c2e',
    messagingSenderId: '133861736811',
    projectId: 'mensameetdatabase',
    storageBucket: 'mensameetdatabase.appspot.com',
    iosBundleId: 'com.example.mensaMeetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRFTEOZPfUoUJCvvh6SdUmRZ0UQlE2Xx8',
    appId: '1:133861736811:ios:267772af3ebbc8e59c4c2e',
    messagingSenderId: '133861736811',
    projectId: 'mensameetdatabase',
    storageBucket: 'mensameetdatabase.appspot.com',
    iosBundleId: 'com.example.mensaMeetApp.RunnerTests',
  );
}
