// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNd-ZR0a0f5Y--Ar0h9AOLWa5d3NrFv-E',
    appId: '1:511369155666:web:acc31d74f1a901773cfb8b',
    messagingSenderId: '511369155666',
    projectId: 'mensameetapp',
    authDomain: 'mensameetapp.firebaseapp.com',
    storageBucket: 'mensameetapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdBRwbb_GMF3MLm3xQbuyQj-NH1mGqZQ8',
    appId: '1:511369155666:android:c3f6a1bd2ce2b7903cfb8b',
    messagingSenderId: '511369155666',
    projectId: 'mensameetapp',
    storageBucket: 'mensameetapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNoBiC1cExZvehGJRF9ugWU9Eu2jQAiw0',
    appId: '1:511369155666:ios:eaf7a3fe9fba3e153cfb8b',
    messagingSenderId: '511369155666',
    projectId: 'mensameetapp',
    storageBucket: 'mensameetapp.appspot.com',
    iosBundleId: 'com.example.mensaMeetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNoBiC1cExZvehGJRF9ugWU9Eu2jQAiw0',
    appId: '1:511369155666:ios:0989660b039fd4db3cfb8b',
    messagingSenderId: '511369155666',
    projectId: 'mensameetapp',
    storageBucket: 'mensameetapp.appspot.com',
    iosBundleId: 'com.example.mensaMeetApp.RunnerTests',
  );
}
