// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUDhUcUxMkmto6UlViM0oIHvQczJ6FbIQ',
    appId: '1:971069456346:web:d6cc6632a8d41fb9a28ae3',
    messagingSenderId: '971069456346',
    projectId: 'mensameetdatabase-7de71',
    authDomain: 'mensameetdatabase-7de71.firebaseapp.com',
    storageBucket: 'mensameetdatabase-7de71.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTNgb4Dr33bejFtDRt0LXUzgHOPJVxbdg',
    appId: '1:971069456346:android:243ee8114d7490e9a28ae3',
    messagingSenderId: '971069456346',
    projectId: 'mensameetdatabase-7de71',
    storageBucket: 'mensameetdatabase-7de71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbt7fr4btoy-kSsaenZGKL-u1GfMWs--0',
    appId: '1:971069456346:ios:84b7fdbc92b198cca28ae3',
    messagingSenderId: '971069456346',
    projectId: 'mensameetdatabase-7de71',
    storageBucket: 'mensameetdatabase-7de71.appspot.com',
    iosBundleId: 'com.example.mensaMeetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbt7fr4btoy-kSsaenZGKL-u1GfMWs--0',
    appId: '1:971069456346:ios:dc927f103356c372a28ae3',
    messagingSenderId: '971069456346',
    projectId: 'mensameetdatabase-7de71',
    storageBucket: 'mensameetdatabase-7de71.appspot.com',
    iosBundleId: 'com.example.mensaMeetApp.RunnerTests',
  );
}
